### ISSUE TITLE
Home page mail doesn't render

### ISSUE THREAD

**Issue by RatonBiswas** [H4kim/portfilio#1]
In your source code, you have a silly mistake, which is mailto.

**Comment by H4kim** [comment]
What wrong with it ? Can you explain!

**Comment by RatonBiswas** [comment]
http://prntscr.com/10m27nzhttp://prntscr.com/10m27nz
In your code, there was a little mistake in mailto. That's why it doesn't work.

**Comment by h4kim-dyze** [comment]
Fixed #4

**Comment by H4kim** [comment]
Fixed by @kushal98 
PR: #4
